name: Build Geode Mod

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: Windows (Win64)
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build the mod
        uses: geode-sdk/build-actions@v1
        with:
          target: Win64
