name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  build:
    name: Windows (Win64)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build the mod
        id: build
        uses: geode-sdk/build-geode-mod@main
        with:
          sdk: latest
          cli: latest
          target: Win64
          build-config: RelWithDebInfo
          path: ./

      - name: Upload the .geode artifact
        uses: actions/upload-artifact@v4
        with:
          name: frame-window-counter-geode
          path: ${{ steps.build.outputs.build-output }}
          if-no-files-found: error
